# Generated by Django 2.2.14 on 2020-09-18 06:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sem',
        ),
        migrations.AddField(
            model_name='book',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Department'),
        ),
        migrations.AddField(
            model_name='book',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.related.ForeignKey, to='store.Semester'),
        ),
        migrations.AddField(
            model_name='semester',
            name='Department',
            field=models.ManyToManyField(to='store.Department'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
