# Generated by Django 2.2.14 on 2020-09-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='busTicket',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='busFrom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='busName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='busTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='busdetails',
            name='busTo',
            field=models.CharField(max_length=40),
        ),
    ]
