# Generated by Django 2.2.14 on 2020-09-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20200914_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='busTicket',
            field=models.IntegerField(default=None),
        ),
    ]
